project_name: "face-classification"
seed: 42

paths:
  zip_path: "data/raw/face classification.v2i.multiclass.zip"
  interim: "data/interim"      # <= qo'shildi (kod kutyapti)
  processed: "data/processed"  # <= qo'shildi (kod kutyapti)
  best_ckpt: "experiments/runs/best_resnet18.pt"
  onnx_path: "experiments/runs/best_resnet18.onnx"


data:
  img_size: 224
  batch_size: 32
  num_workers: 2
  splits: [0.80, 0.10, 0.10]   # train/val/test (agar yo'q bo'lsa)
  normalize_mean: [0.485, 0.456, 0.406]
  normalize_std:  [0.229, 0.224, 0.225]

model:
  backbone: "resnet18"        # resnet18|resnet50|efficientnet_b0 (keyin kengaytirasiz)
  freeze_backbone: false
  num_classes: null           # auto-detect

train:
  epochs: 20
  lr: 0.0003
  weight_decay: 0.0001
  mixed_precision: true
  val_every: 1
  scheduler:
    type: "plateau"
    factor: 0.5
    patience: 2
